src/Entity/Camping.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\CampingRepository;
use Datetime;

#[ORM\Entity(repositoryClass: CampingRepository::class)]

class Camping
{
   
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $idCamping = null;

   
    #[ORM\Column(length:1000)]
    private ?string $nom = null;

   
    #[ORM\Column]
    private ?\DateTime $dateDebut = null;

  
    #[ORM\Column]
    private ?\DateTime $dateFin = null;

   
    #[ORM\Column]
    private ?int $periode = null;

    
    #[ORM\Column]
    private ?float $prix = null;

   
    #[ORM\Column(length:100)]
    private ?string $lieux = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    
    #[ORM\Column(length:255)]
    private $imagec = 'NULL';

   
    #[ORM\Column]
    private ?int $nbr_place = null;

    
    #[ORM\Column]
    private $image = 'NULL';

    public function getIdCamping(): ?int
    {
        return $this->idCamping;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateDebut(): ?\DateTime
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTime $dateDebut): self
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTime
    {
        return $this->dateFin;
    }

    public function setDateFin(\DateTime $dateFin): self
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    public function getPeriode(): ?int
    {
        return $this->periode;
    }

    public function setPeriode(int $periode): self
    {
        $this->periode = $periode;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getLieux(): ?string
    {
        return $this->lieux;
    }

    public function setLieux(string $lieux): self
    {
        $this->lieux = $lieux;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImagec(): ?string
    {
        return $this->imagec;
    }

    public function setImagec(?string $imagec): self
    {
        $this->imagec = $imagec;

        return $this;
    }

    public function getNbrPlace(): ?int
    {
        return $this->nbr_place;
    }

    public function setNbrPlace(int $nbr_place): self
    {
        $this->nbr_place  = $nbr_place ;

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image): self
    {
        $this->image = $image;

        return $this;
    }
    
/**
 * @ORM\ManyToMany(targetEntity="App\Entity\Participation", mappedBy="campings")
 */
private $participations;

public function __construct()
{
    $this->participations = new ArrayCollection();
}

public function getParticipations(): Collection
{
    return $this->participations;
}

public function addParticipation(Participation $participation): self
{
    if (!$this->participations->contains($participation)) {
        $this->participations[] = $participation;
        $participation->addCamping($this);
    }

    return $this;
}

public function removeParticipation(Participation $participation): self
{
    if ($this->participations->contains($participation)) {
        $this->participations->removeElement($participation);
        $participation->removeCamping($this);
    }

    return $this;
}


}

src/Form/CampingType.php
<?php

namespace App\Form;

use App\Entity\Camping;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class CampingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('dateDebut')
            ->add('dateFin')
            ->add('periode')
            ->add('prix')
            ->add('description')
            ->add('imagec', FileType::class, [
                'label' => 'Image du camping',
                'mapped' => false,
                'required' => true,
                'constraints' => [
                    new File([
                        'maxSize' => '2048k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                            'image/gif',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid image (JPEG, PNG or GIF)',
                    ])
                ],
            ])   
        
            ->add('nbr_place')
            ->add('lieux', ChoiceType::class, [
                'choices' => [
                    'Bizerte' => 'Bizerte',
                    'AinDrahem' => 'AinDrahem',
                    'Nabeul' => 'Nabeul',
                    'Beja' => 'Beja',
                    'Klibia' => 'Klibia',
                    'Touzer' => 'Touzer',
                    'Gafsa' => 'Gafsa',
                    'Mahdia' => 'Mahdia',
                    'Haouaria' => 'Haouaria',
                    'Tabarka' => 'Tabarka',
                ]
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Camping::class,
        ]);
    }
}

src/Controller/CampingController.php
<?php

namespace App\Controller;

use App\Entity\Camping;
use App\Form\CampingType;
use App\Repository\CampingRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/camping')]
class CampingController extends AbstractController
{
    #[Route('/', name: 'app_camping_index', methods: ['GET'])]
    public function index(CampingRepository $campingRepository): Response
    {
        return $this->render('camping/index.html.twig', [
            'campings' => $campingRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_camping_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CampingRepository $campingRepository): Response
    {
        $camping = new Camping();
        $form = $this->createForm(CampingType::class, $camping);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
           $startDate = $form->get('dateDebut')->getData();
        $endDate = $form->get('dateFin')->getData();
        
        if ($endDate < $startDate) {
            $this->addFlash('error', 'La date de fin ne peut pas être avant la date de début.');
            return $this->redirectToRoute('app_camping_new');
        }

            $file = $form->get('imagec')->getData();
        $fileName = uniqid().'.'.$file->guessExtension();
        $file->move($this->getParameter('images_directory'), $fileName);

        $camping->setImagec($fileName);
            $campingRepository->save($camping, true);

            return $this->redirectToRoute('app_camping_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('camping/new.html.twig', [
            'camping' => $camping,
            'form' => $form,
        ]);
    }

    #[Route('/{idCamping}', name: 'app_camping_show', methods: ['GET'])]
    public function show(Camping $camping): Response
    {
        return $this->render('camping/show.html.twig', [
            'camping' => $camping,
        ]);
    }

    #[Route('/{idCamping}/edit', name: 'app_camping_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Camping $camping, CampingRepository $campingRepository): Response
    {
        $form = $this->createForm(CampingType::class, $camping);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $campingRepository->save($camping, true);

            return $this->redirectToRoute('app_camping_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('camping/edit.html.twig', [
            'camping' => $camping,
            'form' => $form,
        ]);
    }

    #[Route('/{idCamping}', name: 'app_camping_delete', methods: ['POST'])]
    public function delete(Request $request, Camping $camping, CampingRepository $campingRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$camping->getIdCamping(), $request->request->get('_token'))) {
            $campingRepository->remove($camping, true);
        }

        return $this->redirectToRoute('app_camping_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/camping/_delete_form.html.twig
<form method="post" action="{{ path('app_camping_delete', {'idCamping': camping.idCamping}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ camping.idCamping) }}">
    <button class="btn">Delete</button>
</form>

templates/camping/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}
{% if form_errors(form) %}
    <div class="alert alert-danger">
        {{ form_errors(form) }}
    </div>
{% endif %}

templates/camping/edit.html.twig
{% extends 'base-admin.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
    <main id="main" class="main">
		<section class="section">
			<div class="row">
				<div class="col-lg-12">
					<h1>Edit Camping</h1>

					<div class="col-12">
						<div class="card">
							<div class="card-body">

    {{ include('camping/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_camping_index') }}">back to list</a>

    {{ include('camping/_delete_form.html.twig') }}

    </div>
					</div>
				</div>
			</div>
		</section>

	</main>
{% endblock %}

templates/camping/index.html.twig
{% extends 'base-admin.html.twig' %}

{% block title %}{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <style>
table {
    color: #737373;
    margin: 0 0 1.5em;
    border-collapse: separate;
    border-spacing: 0;
    border-width: 1px 0 0 1px;
    width: 100%;
    font-size: 15px;
}
table thead tr {
    background-color: #262626;
}
table thead tr th {
    color: #383838;
}
table.table {
    color: #737373;
}

th {
    border-width: 0 1px 1px 0;
    font-weight: 700;
}

td {
    border-width: 0 1px 1px 0;
    border-bottom: 1px solid #e6e6e6;
}

th, td {
    padding: 8px;
}

/* Style the "Create new" button */
a.create-new {
  display: block;
  margin-top: 20px;
  padding: 10px 20px;
  background-color: #4CAF50;
  color: white;
  text-align: center;
  text-decoration: none;
}

a.create-new:hover {
  background-color: #3e8e41;
}

/* Style the "show" and "edit" links */
.social-links a {
    font-size: 16px;
    color: #404040;
    -webkit-transition: color 0.4s;
    -moz-transition: color 0.4s;
    -ms-transition: color 0.4s;
    -o-transition: color 0.4s;
    transition: color 0.4s;
}

a.show:hover, a.edit:hover {
  background-color: #ddd;
}
</style>
{% endblock %}

{% block body %}
<main id="main" class="main">
		<section class="section">
			<div class="row">
				<div class="col-lg-12">
					<h1>Camping</h1>

					<div class="col-12">
						<div class="card">
							<div class="card-body">

    <table class="table">
        <thead>
            <tr>
                <th>Nom</th>
                <th>DateDebut</th>
                <th>DateFin</th>
                <th>Periode</th>
                <th>Prix</th>
                <th>Lieux</th>
                <th>Description</th>
                <th>Imagec</th>
                <th>Nbr_place</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for camping in campings %}
            <tr>
                <td>{{ camping.nom }}</td>
                <td>{{ camping.dateDebut ? camping.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ camping.dateFin ? camping.dateFin|date('Y-m-d') : '' }}</td>
                <td>{{ camping.periode }}</td>
                <td>{{ camping.prix }}</td>
                <td>{{ camping.lieux }}</td>
                <td>{{ camping.description }}</td>
                <td>{{ camping.imagec }}</td>
                <td>{{ camping.nbrPlace }}</td>
                <td>
                    <a href="{{ path('app_camping_show', {'idCamping': camping.idCamping}) }}">show</a>
                    <a href="{{ path('app_camping_edit', {'idCamping': camping.idCamping}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_camping_new') }}">Create new</a>
    <a href="{{ path('app_participation_index') }}">check participation</a>

    </div>
					</div>
				</div>
			</div>
		</section>

	</main>

{% endblock %}

templates/camping/new.html.twig
{% extends 'base-admin.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
<main id="main" class="main">
		<section class="section">
			<div class="row">
				<div class="col-lg-12">
					<h1>New Camping</h1>

					<div class="col-12">
						<div class="card">
							<div class="card-body">

    {{ include('camping/_form.html.twig') }}

    <a href="{{ path('app_camping_index') }}">back to list</a>
    </div>
					</div>
				</div>
			</div>
		</section>

	</main>
{% endblock %}

templates/camping/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Camping{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            text-align: left;
            padding: 8px;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #4CAF50;
            color: white;
        }

        tr:hover {background-color: #f5f5f5;}
        .delete-btn {
  background-color: #f44336;
  color: white;
  border: none;
  padding: 8px 16px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 14px;
  margin: 4px 2px;
  cursor: pointer;
  border-radius: 5px;
}

/* Set hover style for delete button */
.delete-btn:hover {
  background-color: #da190b;
}
a {
  color: #4CAF50;
  text-decoration: none;
}

a:hover {
  color: #3e8e41;
}
    </style>
{% endblock %}

{% block body %}
    <h1>Camping</h1>

    <table class="table">
        <tbody>
            
            <tr>
                <th>Nom</th>
                <td>{{ camping.nom }}</td>
            </tr>
            <tr>
                <th>DateDebut</th>
                <td>{{ camping.dateDebut ? camping.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>DateFin</th>
                <td>{{ camping.dateFin ? camping.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Periode</th>
                <td>{{ camping.periode }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ camping.prix }}</td>
            </tr>
            <tr>
                <th>Lieux</th>
                <td>{{ camping.lieux }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ camping.description }}</td>
            </tr>
            <tr>
                <th>Imagec</th>
                <td>{{ camping.imagec }}</td>
            </tr>
            <tr>
                <th>Nbr_place</th>
                <td>{{ camping.nbrPlace }}</td>
            </tr>
            
        </tbody>
    </table>

    <a href="{{ path('app_camping_index') }}">back to list</a>

    <a href="{{ path('app_camping_edit', {'idCamping': camping.idCamping}) }}">edit</a>

    {{ include('camping/_delete_form.html.twig') }}
{% endblock %}